### ISSUE TITLE
UltraProvider does not support list_zones

### ISSUE THREAD

**Issue by squintfox** [octodns/octodns-ultra#40]
Given this YAML:
```
providers:
  ultra:
    class: octodns_ultra.UltraProvider
    # Ultra Account Name (required)
    account: env/ULTRA_ACCOUNT
    # Ultra username (required)
    username: env/ULTRA_USERNAME
    # Ultra password (required)
    password: env/ULTRA_PASSWORD
zones:
  '*':
    sources:
      - ultra
```

And this command:
```
octodns-dump --config-file=config/ultradns-dump.yaml --output-dir=output '*' ultra
```

This error is returned:
```
octodns.manager.ManagerException: dynamic zone=* includes a source, ultra, that does not support `list_zones`
```

Unless I'm missing something, this seems like a very simple change.  I'm going to submit a PR.
